### ISSUE TITLE
Stuck in Root

### ISSUE THREAD

**Issue by MuizU** [badgumby/arch-wsl#2]
I'm stuck in root I cannot leave it.
![image](https://user-images.githubusercontent.com/35157872/102687545-d29a3500-4215-11eb-88c5-043713cb632b.png)

**Comment by MicrowavableMuffin** [comment]
Is root the only user?

`cat /etc/passwd`  
it will probably spit out something like this:
```
root:x:0:0::/root:/bin/bash
bin:x:1:1::/:/usr/bin/nologin
daemon:x:2:2::/:/usr/bin/nologin
mail:x:8:12::/var/spool/mail:/usr/bin/nologin
ftp:x:14:11::/srv/ftp:/usr/bin/nologin
http:x:33:33::/srv/http:/usr/bin/nologin
nobody:x:65534:65534:Nobody:/:/usr/bin/nologin
dbus:x:81:81:System Message Bus:/:/usr/bin/nologin
systemd-journal-remote:x:982:982:systemd Journal Remote:/:/usr/bin/nologin
systemd-network:x:981:981:systemd Network Management:/:/usr/bin/nologin
systemd-resolve:x:980:980:systemd Resolver:/:/usr/bin/nologin
systemd-timesync:x:979:979:systemd Time Synchronization:/:/usr/bin/nologin
systemd-coredump:x:978:978:systemd Core Dumper:/:/usr/bin/nologin
uuidd:x:68:68::/:/usr/bin/nologin
deftclaw:x:1000:1000::/home/deftclaw:/bin/bash
```
`root` is at the top because without root you have nothing.
all these lines ending in `/nologin` are system users for runing services which make your computer work
on a fresh install, __and__ after creating a user your new user will be at the bottom of the list (mine is `deftclaw`) and the end of the
line will indicate the login-shell, (I know the default for vanilla arch is zsh, but I don't like zsh, cannot remember if that is default for WSL also)

if your /etc/passwd does not have an entry near the bottom with either `/bin/bash` or `/bin/zsh` and only `nologin` entries you will need to create a user.

this repo gets you going so you dont _need:_ https://wiki.archlinux.org/index.php/Installation_guide
but to setup your user and get the system going you should read: https://wiki.archlinux.org/index.php/General_recommendations#Users_and_groups

**Comment by MuizU** [comment]
Sorry I fixed it sometime back and forgot to close it
